gui:
  scrollHeight: 15 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  scrollOffMargin: 15 # how many lines to keep before/after the cursor when it reaches the top/bottom of the view; see 'Scroll-off Margin' section below
  scrollOffBehavior: "margin" # one of 'margin' | 'jump'; see 'Scroll-off Margin' section below
  sidePanelWidth: 0.3333 # number from 0 to 1
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible" # one of 'horizontal' | 'flexible' | 'vertical'
  enlargedSideViewLocation: "left" # one of 'left' | 'top'
  language: "auto" # one of 'auto' | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
  timeFormat: "02 Jan 06" # https://pkg.go.dev/time#Time.Format
  shortTimeFormat: "3:04PM"
  showFileTree: false
customCommands:
  - key: "C"
    command: "git czg"
    description: "commit with czg"
    context: "files"
    loadingText: "opening czg commit tool"
    subprocess: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
